### ISSUE TITLE
Separate Header component

### ISSUE THREAD

**Issue by wahidustoz** [ilmhub-uz/pergolahouse#2]
- [x] Separate `header` into a separate component. 
  - `Bosh sahifa` `Kategoriyalar` `Biz haqimizda` linklar qolsin
  - oxiridagi `Post Ad` tugmasi `Bog'lanish`ga o'zgartiring
  - navbardagi linklar hammasida dropdown bor ekan, ularni udalit qilib oddiy linklarga aylantiring, bosganda o'sha sahifaga boradigan qilib

**Comment by shukhratutaboev** [comment]
ok
