### ISSUE TITLE
Separate Hero component

### ISSUE THREAD

**Issue by wahidustoz** [ilmhub-uz/pergolahouse#3]
- [ ] Hero area yani qora rasmni katta joyni alohida HeroArea degan componentga ko'chiring
   - uni ichidagi katta searchbar ichida search input (placeholder: Nima qidiryapsiz?), `Kategoriya` degan select list va `Qidirish degan tugma qolsa bas

**Comment by Abubakr0904** [comment]
Ho'p bo'ladi @wahid-d
