### ISSUE TITLE
Hero image

### ISSUE THREAD

**Issue by wahidustoz** [ilmhub-uz/pergolahouse#39]
Tepadagi hero section ichidagi image ni shu linkdagi image ga ozgartirib koringlar

Ikkalasini ham qo'yib screenshot jonatinglar.

https://apollo-markiz.ru/assets/produkt/pergolla/prp11.jpg
![load-1117308](https://user-images.githubusercontent.com/30383473/152327259-a5796455-dd9d-4d34-94f8-936d2e90aee6.jpg)

**Comment by mutafakkir** [comment]
![Screen Shot 2022-02-03 at 16 25 07](https://user-images.githubusercontent.com/91898505/152334395-d6c39d24-8e93-4513-84f5-cea8ffae4e06.png)
![Screen Shot 2022-02-03 at 16 25 45](https://user-images.githubusercontent.com/91898505/152334331-1f4c1f92-313c-4f58-b508-1bbd679c5405.png)

**Comment by mutafakkir** [comment]
@wahid-d ko'ringchi

**Comment by wahidustoz** [comment]
Tepasidagi qolaversin
