### ISSUE TITLE
English -> Russian

### ISSUE THREAD

**Issue by mutafakkir** [ilmhub-uz/pergolahouse#42]

**Comment by mutafakkir** [comment]
Translating all to Russian

**Comment by mutafakkir** [comment]
@wahid-d I did some mistakes (worked on main branch (ataylabmas)) and when I switched to my own branch, all changes deleted. Then we did all changes on @MrAziz-bek's branch. We will push it soon.

**Comment by MrAziz-bek** [comment]
Merge qilmanglar xatolik ketipti uyga borib qayta jonataman
