### ISSUE TITLE
Newsletter va Footer location section chopish

### ISSUE THREAD

**Issue by wahidustoz** [ilmhub-uz/pergolahouse#43]
<img width="1256" alt="Screen Shot 2022-02-03 at 18 16 25" src="https://user-images.githubusercontent.com/30383473/152350109-0206ce61-991f-4da8-90cf-66b2aa58b507.png">

**Comment by shukhratutaboev** [comment]
![Screenshot from 2022-02-03 18-42-02](https://user-images.githubusercontent.com/89694184/152354204-1fb15999-a0a9-437b-8da0-634defec1448.png)
Yana nimalar qo'shay?

**Comment by wahidustoz** [comment]
@shukhratutaboev Haqimizda -> Tanishamiz

**Comment by wahidustoz** [comment]
@shukhratutaboev Pastga geleraya qo'shasiz cardlardan iborat responsice bolsin
Cardlar ichida rasm yoki video bo'ladi. Instagramdagi Search page da chiqadiku shuanqa
