### ISSUE TITLE
Cleear Console

### ISSUE THREAD

**Issue by Abubakr0904** [ilmhub-uz/pergolahouse#50]
Clear all errors that exists in the console.
Find the reason, fix it, and do all related stuffs.
![Screenshot from 2022-02-03 19-59-25](https://user-images.githubusercontent.com/78490345/152368185-66812f43-dc1e-4acd-b32b-1fb649f24938.png)

**Comment by Abubakr0904** [comment]
Ustoz sizga assign qilib qo'yishimni aytdilar.

**Comment by Abubakr0904** [comment]
Index ni birinchi ochganda shu holat:
1. ![Screenshot from 2022-02-04 11-24-23](https://user-images.githubusercontent.com/78490345/152482425-1f6caeb0-c97b-4458-8fde-993298139326.png)

Boshqa lyuboy pageni (contactus yoki aboutus) ochilganda shu holat:
2. ![Screenshot from 2022-02-04 11-25-29](https://user-images.githubusercontent.com/78490345/152482490-63693cbc-95c3-4fc6-b9ee-6bc876f3461d.png)

Index'ga yana qaytilsa ham 2-rasmdagi holat.

Agar keyin yana refresh qilinsa 1-rasmdagi holat.

**Comment by Abubakr0904** [comment]
@wahid-d @Rizo11 Ustoz shu error'ni to'g'rilashni biladi ustoz degandi, Shuhrat aka.

**Comment by wahidustoz** [comment]
@Rizo11 @Abubakr0904 what the hell is wrong with the console?

<img width="599" alt="image" src="https://user-images.githubusercontent.com/30383473/152496891-74232b07-8488-4a7f-b621-3779e9ccc8d9.png">
