### ISSUE TITLE
Pricing russian text

### ISSUE THREAD

**Issue by wahidustoz** [ilmhub-uz/pergolahouse#59]
<img width="550" alt="image" src="https://user-images.githubusercontent.com/30383473/152499017-7cdadab8-8b8c-407e-a104-48bd7a6041f1.png">

### Shu joy uchun text:
- [x] Header: Bizdagi narxlar
- [x] Subtitle: Biz bozordagi eng uzoq yillik tajribaga ega korxona bo'lishimizga qaramasdan, bizdagi narxlar boshqalarga qaraganda sezilarli darajada hamyonbop. Bizni tanlab adashmadingiz!

## Yuqoridagi text ruscha bo'lsin;

**Comment by mutafakkir** [comment]
Finished
