### ISSUE TITLE
Pricing list

### ISSUE THREAD

**Issue by wahidustoz** [ilmhub-uz/pergolahouse#63]
<img width="993" alt="image" src="https://user-images.githubusercontent.com/30383473/152502861-1beecb22-c400-4b8f-80fd-df24e4ed6215.png">

![image](https://user-images.githubusercontent.com/30383473/152503097-dd8f1d9a-0870-49d5-88a6-f08bef6238b8.jpeg)

**Comment by mutafakkir** [comment]
Can I take this @wahid-d ?

**Comment by wahidustoz** [comment]
@MrAziz-bek Tushintirib bering nima qilish kerakligini. @mutafakkir ha olavering. Lekin sizga boshqa task ham bor. TEzlashtiring buni

**Comment by mutafakkir** [comment]
Ok
