### ISSUE TITLE
ItemCardlarni to'g'rilab chiqing

### ISSUE THREAD

**Issue by Abubakr0904** [ilmhub-uz/pergolahouse#94]
- Min-height berish kerak.
- Bottom-content, ya'ni narx va like turgan joy barcha cardlarda chap va bottom tomondan bir xil masofada tursin.

@mutafakkir Asrorbek priceplan'da siz qilgandingiz shuni. O'sha pull request'ni menga topib berolmaysizmi?
O'shandan qarab to'g'rilab qo'yardim.

**Comment by mutafakkir** [comment]
Qarab chiqtim @Abubakr0904 topa olmadim lekin. lekin aniq esmida min-heigh 550-600px shuni orasida edi. Yozib ko'ring
